CheckForDocumentUpdatesJob:
  cron: "0 42 * * * *"

CheckForMeetingUpdatesJob:
  cron: "0 42 16 * * *"

UpdateChangingContentJob:
  cron: "0 23 */4 * * *"

UpdateTodaysMeetingsJob:
  cron: "0 7 * * * *"

GenerateSitemapJob:
  cron: "0 59 2 * * *"
