CheckForDocumentUpdatesJob:
  cron: "0 42 * * * *"

CheckForMeetingUpdatesJob:
  cron: "0 42 16 * * *"

UpdateChangingContentJob:
  cron: "0 23 */4 * * *"

UpdateSlowlyChangingContentJob:
  cron: "0 17 3 * * *"

UpdateTodaysMeetingsJob:
  cron: "0 7 * * * *"

GenerateSitemapJob:
  cron: "0 59 2 * * *"

UpdateAverageDurationsJob:
  cron: "0 23 1 1 * *"

ExtractDocumentLocationsJob:
  cron: "0 39 1 * * *"
